# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create!(email: ENV['admin_email'], password: ENV['admin_password'], password_confirmation: ENV['admin_password'])
User.create!(email: ENV['user_email'], password: ENV['user_password'], password_confirmation: ENV['user_password'], name: 'さっきー')
# アイドル
Idol.create!(user_id: '1', name: '9nine', about: 'パフォマンスガールズユニット', official_site: 'http://9nine-fan.lespros.co.jp/', official_twitter: 'https://twitter.com/lespros_9nine' ,official_youtube: 'https://www.youtube.com/user/9nineSMEJ', default_image: 'aaa')
Idol.create!(user_id: '1', name: 'ベイビーレイズJAPAN', about: '2018年9月24日解散', official_site: 'http://babyraids.lespros.co.jp/', default_image: '<a target="_blank"  href="https://www.amazon.co.jp/gp/product/B07H846J33/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B07H846J33&linkCode=as2&tag=skiymaaa0123-22&linkId=d31ffcf8aff6e9594a5cec22e3f35310"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B07H846J33&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=skiymaaa0123-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=skiymaaa0123-22&l=am2&o=9&a=B07H846J33" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />')
Idol.create!(user_id: '1', name: '大阪☆春夏秋冬', about: '', official_site: 'https://syukasyun.com/', default_image: '<a target="_blank"  href="https://www.amazon.co.jp/gp/product/B0863NSY4Q/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B0863NSY4Q&linkCode=as2&tag=skiymaaa0123-22&linkId=fd5e4e1bf1b70d500bcc9b0ded5418a4"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B0863NSY4Q&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=skiymaaa0123-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=skiymaaa0123-22&l=am2&o=9&a=B0863NSY4Q" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />')
Idol.create!(user_id: '1', name: 'EMPiRE', about: '', official_site: 'https://empire-official.com/', default_image: '<a target="_blank"  href="https://www.amazon.co.jp/gp/product/B07ZNLZYF5/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B07ZNLZYF5&linkCode=as2&tag=skiymaaa0123-22&linkId=9338d87dffbe9b92bb718126f44e8042"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B07ZNLZYF5&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=skiymaaa0123-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=skiymaaa0123-22&l=am2&o=9&a=B07ZNLZYF5" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />')
Idol.create!(user_id: '1', name: 'GANGPARADE', about: '', official_site: 'https://www.gangparade.com/', default_image: '<a target="_blank"  href="https://www.amazon.co.jp/gp/product/B07L9NB2M3/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B07L9NB2M3&linkCode=as2&tag=skiymaaa0123-22&linkId=7437de1325e926fd3c5da91ead99b172"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B07L9NB2M3&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=skiymaaa0123-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=skiymaaa0123-22&l=am2&o=9&a=B07L9NB2M3" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />')
Idol.create!(user_id: '1', name: 'CARRY ROOSE', about: '', official_site: 'https://www.carryloose.com/', default_image: '<a target="_blank"  href="https://www.amazon.co.jp/gp/product/B07XB4CV99/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B07XB4CV99&linkCode=as2&tag=skiymaaa0123-22&linkId=0a444d6127adfb2cd20a12f3226bf62f"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B07XB4CV99&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=skiymaaa0123-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=skiymaaa0123-22&l=am2&o=9&a=B07XB4CV99" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />')
Idol.create!(user_id: '1', name: 'BiS', about: '', official_site: 'https://www.brandnewidolsociety.tokyo/', default_image: '<a target="_blank"  href="https://www.amazon.co.jp/gp/product/B081WQY65G/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B081WQY65G&linkCode=as2&tag=skiymaaa0123-22&linkId=df0426e656067490d9ffa3db35689ebf"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B081WQY65G&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=skiymaaa0123-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=skiymaaa0123-22&l=am2&o=9&a=B081WQY65G" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />')
Idol.create!(user_id: '1', name: 'BiSH', about: '', official_site: 'https://www.bish.tokyo/', default_image: '<a target="_blank"  href="https://www.amazon.co.jp/gp/product/B07NXF5VJ1/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B07NXF5VJ1&linkCode=as2&tag=skiymaaa0123-22&linkId=c1fd445fac6632996a51e9fd01c8af80"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B07NXF5VJ1&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=skiymaaa0123-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=skiymaaa0123-22&l=am2&o=9&a=B07NXF5VJ1" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />')
# 場所
Place.create!(user_id: '1', name: 'ラゾーナ川崎プラザ', address: '神奈川県川崎市幸区堀川町72-1', about: 'ルーファ広場', official_site: 'https://mitsui-shopping-park.com/lazona-kawasaki/')
Place.create!(user_id: '1', name: 'サンシャインシティ', address: '東京都豊島区東池袋３丁目１', about: '噴水広場', official_site: 'https://sunshinecity.jp/')
Place.create!(user_id: '1', name: 'ラ チッタデッラ', address: '神奈川県川崎市川崎区小川町４−１', about: '', official_site: 'https://lacittadella.co.jp/')
Place.create!(user_id: '1', name: 'ららぽーと豊洲', address: '東京都江東区豊洲2-4-9', about: '', official_site: 'https://mitsui-shopping-park.com/lalaport/toyosu/')
Place.create!(user_id: '1', name: '新宿マルイ メン', address: '東京都新宿区新宿５丁目１６−４', about: '', official_site: 'https://www.0101.co.jp/074/')
Place.create!(user_id: '1', name: 'タワーレコード 横浜ビブレ', address: '神奈川県横浜市西区南幸２丁目１５−１３ GF 横浜ビブレ', about: 'niigo広場', official_site: 'https://tower.jp/store/kanto/YokohamaVIVRE')